name: task1
channels:
 - conda-forge
 - defaults
 - pytorch
dependencies:
 - baumwelch=0.3.5
 - ngram=1.3.12
 - numpy=1.19.2
 - openfst=1.8.0
 - pandas=1.1.3
 - pip=20.3
 - pynini=2.1.3
 - python=3.8.5
 - pytorch=1.6.0
 - pip:
   - fairseq==0.10.1
